---
# Example configuration file for macOS bootstrap
# Copy this file to config.local.yml and customize as needed
# The playbook will automatically load config.local.yml if it exists

# Git configuration
git_user_name: "Your Name"
git_user_email: "your.email@example.com"

# Additional Homebrew packages to install
additional_homebrew_packages:
  - ripgrep      # Better grep
  - fd           # Better find
  - bat          # Better cat
  - exa          # Better ls
  - fzf          # Fuzzy finder
  - gh           # GitHub CLI
  - httpie       # HTTP client
  - ansible-lint # Ansible linting

# Additional Homebrew cask applications
additional_homebrew_casks:
  - postman          # API development
  - tableplus        # Database management
  - figma            # Design tool
  - spotify          # Music streaming
  - discord          # Communication
  - notion           # Note taking

# Override default packages (optional)
# homebrew_packages:
#   - git
#   - curl
#   - wget
#   - your-custom-packages

# Override default applications (optional)
# homebrew_casks:
#   - visual-studio-code
#   - your-preferred-apps

# Customize macOS settings
macos_settings:
  # Dock settings
  dock_autohide: true
  dock_position: "bottom"  # bottom, left, right
  dock_tile_size: 48
  
  # Finder settings
  finder_show_hidden_files: true
  finder_show_extensions: true
  
  # Trackpad settings
  trackpad_tap_to_click: true
  trackpad_three_finger_drag: true

# Development environment
install_development_tools: true
configure_git: true
configure_dotfiles: false

# Dotfiles configuration (if you want to use your own dotfiles)
# dotfiles_repo: "https://github.com/yourusername/dotfiles.git"
# dotfiles_home: "~"